name: Frictionless
on:
  push:
    paths:
      - 'schema/examples/*.csv'
      - 'schema/tables/*.json'
      - 'datapackage.json'
  pull_request:
    paths:
      - 'schema/examples/*.csv'
      - 'schema/tables/*.json'
      - 'datapackage.json'
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate tables
        uses: frictionlessdata/repository@v2
        with:
          packages: datapackage.json
