name: Generate Table Schemas
on:
  push:
    paths:
      - recombinant-published-schema-urls.txt
      - scripts/generate_table_schemas.py
      - scripts/validate_table_schemas.py
      - '.github/workflows/generate-table-schemas.yml'
  workflow_dispatch:
  schedule:
    - cron: '25 5 * * 1'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt requests
      - run: python scripts/generate_table_schemas.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update table schemas'
          file_pattern: |
            dictionaries/*.json
            schema/tables/*.json
            schema/examples/*.csv
      - run: python scripts/validate_table_schemas.py --delay 10
