name: Generate Table Schemas
on:
  push:
    paths:
      - dictionaries/*.json
      - docs/choices/*.md
  workflow_dispatch:
    # Trigger on workflow file/script changes
    paths:
      - .github/workflows/generate-table-schemas.yml
      - scripts/generate_table_schemas.py
permissions:
  contents: read # Removed write permission
jobs:
  generate-table-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Standard depth
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python scripts/generate_table_schemas.py