name: Generate Table Schemas
on:
  push:
    paths:
      - dictionaries/*.json
      - docs/choices/*.md
  workflow_dispatch:
permissions:
  contents: write #permission
jobs:
  generate-table-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Standard depth
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python scripts/generate_table_schemas.py
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add schema/* 
          git commit -m "Update Schema docs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
