name: Generate Dataset Docs
on:
  push:
    paths:
      - recombinant-published-schema-urls.txt
  schedule:
    - cron: '0 0 * * 0' # Weekly run
  workflow_dispatch:
permissions:
  contents: read # Removed write permission
jobs:
  generate-dataset-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Standard depth
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python scripts/generate_dataset_docs.py
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/* 
          git commit -m "Update Reference docs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
