name: Validate With API
on:
  workflow_dispatch:
    inputs:
      csv:
        description: 'CSV file to validate'
        required: true
      schema:
        description: 'Schema JSON file'
        required: true
permissions:
  contents: write
jobs:
  validate-with-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Standard depth
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python scripts/validate_table_schemas.py --csv "$CSV" --schema "$SCHEMA" --delay 10
        env:
          CSV: ${{ inputs.csv }}
          SCHEMA: ${{ inputs.schema }}
